// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backendForms.Data;

#nullable disable

namespace backendForms.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("backendForms.Campo", b =>
                {
                    b.Property<int>("IdCampo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCampo"));

                    b.Property<Guid?>("EncuestaIdEncuesta")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdEncuesta")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Requerido")
                        .HasColumnType("bit");

                    b.Property<string>("TipoCampo")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("IdCampo");

                    b.HasIndex("EncuestaIdEncuesta");

                    b.ToTable("Campos");
                });

            modelBuilder.Entity("backendForms.Encuesta", b =>
                {
                    b.Property<Guid>("IdEncuesta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdEncuesta");

                    b.ToTable("Encuestas");
                });

            modelBuilder.Entity("backendForms.Respuesta", b =>
                {
                    b.Property<int>("IdRespuesta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRespuesta"));

                    b.Property<int>("IdCampo")
                        .HasColumnType("int");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("IdRespuesta");

                    b.HasIndex("IdCampo");

                    b.ToTable("Respuestas");
                });

            modelBuilder.Entity("backendForms.Campo", b =>
                {
                    b.HasOne("backendForms.Encuesta", null)
                        .WithMany("Campos")
                        .HasForeignKey("EncuestaIdEncuesta");
                });

            modelBuilder.Entity("backendForms.Respuesta", b =>
                {
                    b.HasOne("backendForms.Campo", "Campo")
                        .WithMany("Respuestas")
                        .HasForeignKey("IdCampo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campo");
                });

            modelBuilder.Entity("backendForms.Campo", b =>
                {
                    b.Navigation("Respuestas");
                });

            modelBuilder.Entity("backendForms.Encuesta", b =>
                {
                    b.Navigation("Campos");
                });
#pragma warning restore 612, 618
        }
    }
}
